version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/consensus"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/dbc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/seals"
    schedule:
      interval: "weekly"
