[package]
name = "client_side_validation"
version = "0.5.0-rc.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Client-side validation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "client-side-validation"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "bp-dbc", "bp-seals", "commit_verify", "strict_encoding", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
amplify = "3.7.1"
strict_encoding = "1.5.1"
commit_verify = "0.5.0"
single_use_seals = "0.5.1"
bp-dbc = { version = "0.5.0-rc.1", path = "./dbc", optional = true, default-features = false }
bp-seals = { version = "0.5.0-rc.1", path = "./seals", optional = true, default-features = false }

[features]
default = []
all = []


[workspace]
members = [".", "dbc", "seals"]
default-members = [".", "dbc", "seals"]
