[workspace]
members = [
    "consensus",
    "dbc",
    "seals",
    "."
]
default-members = [
    "consensus",
    "dbc",
    "seals",
    "."
]

[workspace.package]
version = "0.10.11"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/BP-WG"
repository = "https://github.com/BP-WG/bp-core"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.5.0"
strict_encoding = "2.6.1"
strict_types = "1.6.3"
commit_verify = "0.11.0-beta.1"
single_use_seals = "0.11.0-beta.1"
bp-consensus = { version = "0.10.11", path = "consensus" }
bp-dbc = { version = "0.10.11", path = "./dbc" }
bp-seals = { version = "0.10.11", path = "./seals" }
secp256k1 = { version = "0.27.0", features = ["global-context"] }
serde_crate = { package = "serde", version = "1", features = ["derive"] }

[package]
name = "bp-core"
version = { workspace = true }
description = "Bitcoin protocol core library (BP Core Lib)"
keywords = ["lnp-bp", "smart-contracts", "bitcoin", "blockchain"]
categories = ["cryptography"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "primitives", "dbc", "seals"]

[lib]
name = "bp"
path = "src/lib.rs"

[[bin]]
name = "bpcore-stl"
required-features = ["stl"]

[dependencies]
amplify = { workspace = true }
strict_encoding = { workspace = true }
strict_types = { workspace = true, optional = true }
commit_verify = { workspace = true }
single_use_seals = { workspace = true }
bp-consensus = { workspace = true }
bp-dbc = { workspace = true }
bp-seals = { workspace = true }
serde_crate = { workspace = true, optional = true }

[features]
default = []
all = ["chrono", "serde", "stl"]
chrono = ["bp-consensus/chrono"]
serde = [
    "serde_crate",
    "bp-consensus/serde",
    "bp-dbc/serde",
    "bp-seals/serde",
]
stl = ["strict_types", "strict_types/base64", "bp-consensus/stl", "commit_verify/stl"]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "v0.11" }
single_use_seals = { git = "https://github.com/LNP-BP/client_side_validation", branch = "v0.11" }
