[package]
name = "bp-core"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Client-side validation library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "bitcoin"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "bp-dbc", "bp-seals"]

[lib]
name = "bp"
path = "src/lib.rs"

[[bin]]
name = "bp"
path = "src/main.rs"
required-features = ["shell"]

[dependencies]
amplify = "3.9.1"
strict_encoding = { version = "1.7.4", features = ["bitcoin", "miniscript", "derive"] }
commit_verify = "0.5.11"
single_use_seals = "0.5.5"
bp-dbc = { version = "0.5.0", path = "./dbc" }
bp-seals = { version = "0.5.0", path = "./seals" }
bitcoin = "0.27.0"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }
clap = { version = "3.0", optional = true, features = ["derive"] }
descriptor-wallet = { version = "0.5.2", optional = true }

[features]
default = []
all = ["async", "serde", "shell"]
shell = ["clap", "descriptor-wallet"]
async = ["bp-seals/async"]
serde = ["amplify/serde", "bitcoin/use-serde",
         "commit_verify/serde", "bp-dbc/serde", "bp-seals/serde",
         "serde_crate", "serde_with"]

[workspace]
members = [".", "dbc", "seals"]
default-members = [".", "dbc", "seals"]
