[workspace]
members = [
    "primitives",
    "dbc",
    "seals",
    "."
]
default-members = [
    "primitives",
    "dbc",
    "seals",
    "."
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/BP-WG"
repository = "https://github.com/BP-WG/bp-core"
rust-version = "1.66" # Due to strict encoding library (caused by GAD)
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.0.0"
strict_encoding = "2.2.0"
commit_verify = "0.10.2"
single_use_seals = "0.10.0"

[package]
name = "bp-core"
version = "0.10.3"
description = "Bitcoin protocol core library (BP Core Lib)"
keywords = ["lnp-bp", "smart-contracts", "bitcoin", "blockchain"]
categories = ["cryptography"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "primitives", "dbc", "seals"]

[lib]
name = "bp"
path = "src/lib.rs"

[[bin]]
name = "bpcore-stl"
required-features = ["stl"]

[dependencies]
amplify = { workspace = true }
strict_encoding = { workspace = true }
strict_types = { version = "1.2.0", optional = true }
commit_verify = { workspace = true }
single_use_seals = { workspace = true }
bp-primitives = { version = "0.10.3", path = "./primitives" }
bp-dbc = { version = "0.10.3", path = "./dbc" }
bp-seals = { version = "0.10.3", path = "./seals" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde", "stl"]
serde = [
    "serde_crate",
    "bp-dbc/serde",
    "bp-seals/serde",
]
stl = ["strict_types", "strict_types/base64", "bp-primitives/stl", "commit_verify/stl"]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
strict_types = { git = "https://github.com/strict-types/strict-types" }
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation" }
