[package]
name = "bp-core"
version = "0.9.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin Protocol Core Library (BP Core Lib)"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "bitcoin"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "dbc", "seals", "dbc-legacy", "seals-legacy"]

[lib]
name = "bp"
path = "src/lib.rs"

[dependencies]
amplify = "3.13.0"
strict_encoding = "0.9.0"
commit_verify = "0.9.0"
single_use_seals = "0.9.0"
bitcoin = "0.29.2"
bp-dbc = { version = "0.9.0", path = "./dbc" }
bp-seals = { version = "0.9.0", path = "./seals" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.14", optional = true }

[features]
default = []
all = ["serde"]
serde = ["amplify/serde", "bitcoin/serde",
         "commit_verify/serde", "bp-dbc/serde", "bp-seals/serde",
         "serde_crate", "serde_with"]

[workspace]
members = [".", "raw", "dbc", "seals"]
default-members = [".", "raw", "dbc", "seals"]
