[package]
name = "bp-core"
version = "0.5.0-beta.3"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Client-side validation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "bp-dbc", "bp-seals"]

[lib]
name = "bp"
path = "src/lib.rs"

[dependencies]
amplify = "3.8.2"
strict_encoding = { version = "1.6.1", features = ["bitcoin", "miniscript", "derive"] }
commit_verify = "0.5.6"
single_use_seals = "0.5.5"
bp-dbc = { version = "0.5.0-beta.1", path = "./dbc" }
bp-seals = { version = "0.5.0-beta.1", path = "./seals" }
bitcoin = "0.27.0"

[features]
default = []
all = ["async"]
async = ["bp-seals/async"]

[workspace]
members = [".", "dbc", "seals"]
default-members = [".", "dbc", "seals"]
