codecov:
  require_ci_to_pass: no

coverage:
  precision: 1
  round: nearest
  range: "0...95"
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 75%
        threshold: 1%