[package]
name = "bp-dbc"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Deterministic bitcoin commitments library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "../README.md"
edition = "2018"

[lib]
name = "dbc"
path = "src/lib.rs"

[dependencies]
amplify = "3.9.1"
bitcoin = "0.27.1"
secp256k1 = { version = "0.20.3", features = ["global-context"] }
bitcoin_scripts = "0.5.0"
descriptors = "0.5.0"
strict_encoding = "1.7.4"
commit_verify = "0.5.11"
miniscript = "6.0.1"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[features]
default = []
all = ["serde"]
serde = ["amplify/serde", "bitcoin/use-serde", "bitcoin_scripts/serde", "commit_verify/serde", "miniscript/serde", "serde_crate", "serde_with"]
