[package]
name = "bp-seals"
version = "0.7.0-alpha.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin single-use-seals library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "../README.md"
edition = "2018"

[lib]
name = "seals"
path = "src/lib.rs"

[dependencies]
amplify = "3.12.0"
bitcoin = { version = "0.28.1", features = ["rand"] }
single_use_seals = "0.7.0-alpha.1"
commit_verify = "0.7.0-alpha.7"
strict_encoding = "1.8.0"
lnpbp_bech32 = "0.7.0"
bp-dbc = { version = "0.7.0-alpha.1", path = "../dbc" }
async-trait = { version = "0.1.51", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[features]
default = []
all = ["async", "serde", "miniscript"]
miniscript = ["bp-dbc/miniscript"]
async = ["single_use_seals/async", "async-trait"]
serde = ["amplify/serde", "bitcoin/use-serde", "commit_verify/serde", "lnpbp_bech32/serde", "bp-dbc/serde", "serde_crate", "serde_with"]
