[package]
name = "bp-seals"
version = "0.10.0-beta.1"
description = "Bitcoin protocol single-use-seals library"
keywords = ["lnp-bp", "bitcoin", "blockchain", "smart-contracts", "single-use-seals"]
categories = ["cryptography", "encoding"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "../README.md"

[lib]
name = "seals"
path = "src/lib.rs"

[dependencies]
amplify = "4.0.0-beta.10"
single_use_seals = "0.10.0-beta.1"
commit_verify = "0.10.0-beta.2"
strict_encoding = "2.0.0-beta.5"
baid58 = "0.2.0"
bp-primitives = { version = "0.10.0-beta.1", path = "../primitives" }
bp-dbc = { version = "0.10.0-beta.1", path = "../dbc" }
rand = "0.8.5"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde"]
serde = ["amplify/serde", "commit_verify/serde", "bp-dbc/serde", "serde_crate"]

[package.metadata.docs.rs]
features = [ "all" ]
