[package]
name = "bp-seals"
version = "0.10.0-beta.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin protocol single-use-seals library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "../README.md"
edition = "2021"
rust-version = "1.66.0"

[lib]
name = "seals"
path = "src/lib.rs"

[dependencies]
amplify = "4.0.0-beta.10"
single_use_seals = "0.10.0-beta.1"
commit_verify = "0.10.0-beta.1"
strict_encoding = "2.0.0-beta.5"
bp-primitives = { version = "0.10.0-beta.1", path = "../primitives" }
bp-dbc = { version = "0.10.0-beta.1", path = "../dbc" }
rand = "0.8.5"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde"]
serde = ["amplify/serde", "commit_verify/serde", "bp-dbc/serde", "serde_crate"]

[package.metadata.docs.rs]
features = [ "all" ]
