[package]
name = "bp-seals"
version = "0.5.0-alpha.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin single-use-seals library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "client-side-validation"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "README.md"
edition = "2018"

[lib]
name = "seals"
path = "src/lib.rs"

[dependencies]
amplify = "3.8.2"
bitcoin = "0.27.0"
single_use_seals = "0.5.5"
commit_verify = "0.5.6"
strict_encoding = "1.6.1"
lnpbp_bech32 = "0.5.0-beta.1"
bp-dbc = { version = "0.5.0-alpha.1", path = "../dbc" }
